spring:
  datasource:
    url: jdbc:mysql://tempdb.clzby4qsanjs.ap-northeast-2.rds.amazonaws.com:3306/money
    username: root
    password: 20190976sswu
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
        globally_quoted_identifiers: true
server:
  port: 8083
logging:
  level:
    org.springframework.data: DEBUG

cloud:
  aws:
    credentials:
      access-key: AKIAT2DUCVSUV4QGXN57
      secret-key: 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
    s3:
      bucket: money-bucket-aws
    region:
      static: ap-northeast-2
    stack:
      auto: false